export interface DealMemo {
  id: string
  date: string
  content: string
}

export interface DealStatus {
  checked: boolean
  date: string
}

export interface OptionItem {
  id: string
  category: string
  optionName: string
  amount: number
}

export interface DealInfo {
  vinNumber: string
  carModel: string
  maker: string
  color: string
  grade: string
  year: string
  mileage: string
  modelType: string
  salesPrice: number
  discount: number
  carType: string
  options: OptionItem[]
  dealMemos: DealMemo[]
  statuses: {
    lineContact: DealStatus
    contract: DealStatus
    followUp1: DealStatus
    followUp2: DealStatus
    documents: DealStatus
    payment: DealStatus
    delivered: DealStatus
  }
  noFollowUp: boolean
  // 営業ダッシュボード用フィールド
  paymentMethod?: 'cash' | 'loan' | ''
  hasTradeIn?: boolean
  isInstantClose?: boolean
  dealChannel?: 'visit' | 'phone' | 'online'
}

export interface Customer {
  id: string
  name: string
  furigana: string
  phone: string
  phone2: string
  email: string
  email2: string
  postalCode: string
  address1: string
  address2: string
  salesRep: string
  addedDate: string
  store: string
  contractDate: string
  deliveryStatus: string
  carType: string
  address: string
  memo: string
  carModel: string
  vinNumber: string
  dealInfo: DealInfo
}

export const DUMMY_CUSTOMERS: Customer[] = [
  {
    id: 'C001',
    name: '山田 太郎',
    furigana: 'ヤマダ タロウ',
    phone: '090-1234-5678',
    phone2: '',
    email: 'yamada@example.com',
    email2: '',
    postalCode: '460-0008',
    address1: '愛知県名古屋市中区栄',
    address2: '1-2-3 サンプルビル4F',
    salesRep: '高橋',
    addedDate: '2025-01-05',
    store: '本店',
    contractDate: '2025-01-10',
    deliveryStatus: '納車待ち',
    address: '愛知県名古屋市中区栄1-2-3 サンプルビル4F',
    memo: '初回商談済み',
    carType: '新車',
    carModel: 'プリウス',
    vinNumber: '12345678901234567',
    dealInfo: {
      vinNumber: '12345678901234567',
      carModel: 'プリウス',
      maker: 'トヨタ',
      color: '白',
      grade: 'S',
      year: '2018',
      mileage: '45000',
      modelType: 'ZVW30',
      salesPrice: 1380000,
      discount: 0,
      carType: '新車',
      options: [
        { id: 'opt1', category: '内装', optionName: 'フロアマット', amount: 15000 },
        { id: 'opt2', category: '外装', optionName: 'ドアバイザー', amount: 12000 },
      ],
      dealMemos: [
        { id: '1', date: '2025-01-10', content: '来店ヒアリング' },
        { id: '2', date: '2025-01-12', content: '見積提示、家族と要相談とのこと' },
      ],
      statuses: {
        lineContact: { checked: true, date: '2025-01-05' },
        contract: { checked: true, date: '2025-01-10' },
        followUp1: { checked: false, date: '' },
        followUp2: { checked: false, date: '' },
        documents: { checked: false, date: '' },
        payment: { checked: false, date: '' },
        delivered: { checked: false, date: '' },
      },
      noFollowUp: false,
      paymentMethod: 'loan',
      hasTradeIn: true,
      isInstantClose: false,
      dealChannel: 'visit',
    },
  },
  {
    id: 'C002',
    name: '佐藤 花子',
    furigana: 'サトウ ハナコ',
    phone: '080-9876-5432',
    phone2: '052-123-4567',
    email: 'sato.hanako@example.com',
    email2: '',
    postalCode: '464-0850',
    address1: '愛知県名古屋市千種区今池',
    address2: '5-6-7',
    salesRep: '鈴木',
    addedDate: '2025-01-06',
    store: '支店A',
    contractDate: '2025-01-08',
    deliveryStatus: '納車済み',
    address: '愛知県名古屋市千種区今池5-6-7',
    memo: '紹介案件',
    carType: '中古車',
    carModel: 'アクア',
    vinNumber: '98765432109876543',
    dealInfo: {
      vinNumber: '98765432109876543',
      carModel: 'アクア',
      maker: 'トヨタ',
      color: '黒',
      grade: 'G',
      year: '2020',
      mileage: '28000',
      modelType: 'NHP10',
      salesPrice: 980000,
      discount: 0,
      carType: '中古車',
      options: [
        { id: 'opt3', category: 'ナビ', optionName: 'カーナビ', amount: 35000 },
      ],
      dealMemos: [
        { id: '3', date: '2025-01-05', content: '電話問い合わせ' },
        { id: '4', date: '2025-01-08', content: '来店、即決' },
      ],
      statuses: {
        lineContact: { checked: true, date: '2025-01-06' },
        contract: { checked: true, date: '2025-01-08' },
        followUp1: { checked: true, date: '2025-01-12' },
        followUp2: { checked: false, date: '' },
        documents: { checked: true, date: '2025-01-15' },
        payment: { checked: true, date: '2025-01-18' },
        delivered: { checked: true, date: '2025-01-20' },
      },
      noFollowUp: false,
      paymentMethod: 'cash',
      hasTradeIn: false,
      isInstantClose: true,
      dealChannel: 'visit',
    },
  },
  {
    id: 'C003',
    name: '田中 一郎',
    furigana: 'タナカ イチロウ',
    phone: '070-1111-2222',
    phone2: '',
    email: 'tanaka@example.com',
    email2: 'tanaka.sub@example.com',
    postalCode: '450-0002',
    address1: '愛知県名古屋市中村区名駅',
    address2: '3-4-5 ABCビル10F',
    salesRep: '佐藤',
    addedDate: '2025-01-08',
    store: '本店',
    contractDate: '2025-01-15',
    deliveryStatus: '納車待ち',
    address: '愛知県名古屋市中村区名駅3-4-5 ABCビル10F',
    memo: '法人契約',
    carType: '中古車',
    carModel: 'カローラ',
    vinNumber: '11122233344455566',
    dealInfo: {
      vinNumber: '11122233344455566',
      carModel: 'カローラ',
      maker: 'トヨタ',
      color: 'シルバー',
      grade: 'G',
      year: '2019',
      mileage: '35000',
      modelType: 'NRE210',
      salesPrice: 1250000,
      discount: 0,
      carType: '中古車',
      options: [],
      dealMemos: [
        { id: '5', date: '2025-01-12', content: 'オンライン商談' },
      ],
      statuses: {
        lineContact: { checked: true, date: '2025-01-08' },
        contract: { checked: true, date: '2025-01-15' },
        followUp1: { checked: false, date: '' },
        followUp2: { checked: false, date: '' },
        documents: { checked: false, date: '' },
        payment: { checked: false, date: '' },
        delivered: { checked: false, date: '' },
      },
      noFollowUp: false,
      paymentMethod: 'loan',
      hasTradeIn: false,
      isInstantClose: false,
      dealChannel: 'online',
    },
  },
  {
    id: 'C004',
    name: '鈴木 次郎',
    furigana: 'スズキ ジロウ',
    phone: '090-3333-4444',
    phone2: '',
    email: '',
    email2: '',
    postalCode: '468-0073',
    address1: '愛知県名古屋市天白区塩釜口',
    address2: '2-1-1',
    salesRep: '田中',
    addedDate: '2025-01-10',
    store: '支店B',
    contractDate: '2025-01-15',
    deliveryStatus: '納車待ち', 
    address: '愛知県名古屋市天白区塩釜口2-1-1',
    memo: '下取り希望',
    carType: '中古車',
    carModel: 'フィット',
    vinNumber: '77788899900011122',
    dealInfo: {
      vinNumber: '77788899900011122',
      carModel: 'フィット',
      maker: 'ホンダ',
      color: 'ブルー',
      grade: 'G',
      year: '2019',
      mileage: '42000',
      modelType: 'GK3',
      salesPrice: 980000,
      discount: 20000,
      carType: '中古車',
      options: [
        { id: 'opt4', category: 'タイヤ', optionName: 'スタッドレスタイヤ', amount: 60000 },
      ],
      dealMemos: [
        { id: '4', date: '2025-01-10', content: '下取り車査定' },
        { id: '5', date: '2025-01-12', content: '見積提示、契約決定' },
      ],
      statuses: {
        lineContact: { checked: true, date: '2025-01-10' },
        contract: { checked: true, date: '2025-01-15' },
        followUp1: { checked: true, date: '2025-01-11' },
        followUp2: { checked: false, date: '' },
        documents: { checked: true, date: '2025-01-15' },
        payment: { checked: false, date: '' },
        delivered: { checked: false, date: '' },
      },
      noFollowUp: false,
      paymentMethod: 'cash',
      hasTradeIn: true,
      isInstantClose: false,
      dealChannel: 'visit',
    },
  },
  {
    id: 'C005',
    name: '伊藤 美咲',
    furigana: 'イトウ ミサキ',
    phone: '080-5555-6666',
    phone2: '052-987-6543',
    email: 'ito.misaki@example.com',
    email2: '',
    postalCode: '461-0001',
    address1: '愛知県名古屋市東区泉',
    address2: '1-23-45',
    salesRep: '山本',
    addedDate: '2025-01-12',
    store: '本店',
    contractDate: '',
    deliveryStatus: '商談中',
    address: '愛知県名古屋市東区泉1-23-45',
    memo: '予算要確認',
    carType: '新車',
    carModel: '', 
    vinNumber: '',
    dealInfo: {
      vinNumber: '',
      carModel: '',
      maker: '',
      color: '',
      grade: '',
      year: '',
      mileage: '',
      modelType: '',
      salesPrice: 0,
      discount: 0,
      carType: '新車',
      options: [],
      dealMemos: [
        { id: '6', date: '2025-01-12', content: '初回相談、複数車種検討中' },
      ],
      statuses: {
        lineContact: { checked: false, date: '' },
        contract: { checked: false, date: '' },
        followUp1: { checked: false, date: '' },
        followUp2: { checked: false, date: '' },
        documents: { checked: false, date: '' },
        payment: { checked: false, date: '' },
        delivered: { checked: false, date: '' },
      },
      noFollowUp: false,
      paymentMethod: '',
      hasTradeIn: false,
      isInstantClose: false,
      dealChannel: 'online',
    },
  },
  {
    id: 'C006',
    name: '中村 健太',
    furigana: 'ナカムラ ケンタ',
    phone: '080-7777-8888',
    phone2: '',
    email: 'nakamura.k@example.com',
    email2: '',
    postalCode: '453-0015',
    address1: '愛知県名古屋市中村区椿町',
    address2: '21-2',
    salesRep: '高橋',
    addedDate: '2025-01-14',
    store: '本店',
    contractDate: '2025-01-20',
    deliveryStatus: '納車待ち',
    address: '愛知県名古屋市中村区椿町21-2',
    memo: 'リピーター顧客',
    carType: '中古車',
    carModel: 'ヴォクシー',
    vinNumber: '11122233344455566',
    dealInfo: {
      vinNumber: '11122233344455566',
      carModel: 'ヴォクシー',
      maker: 'トヨタ',
      color: 'シルバー',
      grade: 'ZS',
      year: '2019',
      mileage: '35000',
      modelType: 'ZRR80',
      salesPrice: 2180000,
      discount: 0,
      carType: '中古車',
      options: [
        { id: 'opt4', category: 'ナビ', optionName: 'カーナビ', amount: 40000 },
        { id: 'opt5', category: '外装', optionName: 'コーティング', amount: 50000 },
      ],
      dealMemos: [
        { id: '7', date: '2025-01-14', content: 'ファミリーカー希望' },
      ],
      statuses: {
        lineContact: { checked: true, date: '2025-01-14' },
        contract: { checked: true, date: '2025-01-20' },
        followUp1: { checked: false, date: '' },
        followUp2: { checked: false, date: '' },
        documents: { checked: false, date: '' },
        payment: { checked: false, date: '' },
        delivered: { checked: false, date: '' },
      },
      noFollowUp: false,
      paymentMethod: 'loan',
      hasTradeIn: true,
      isInstantClose: false,
      dealChannel: 'visit',
    },
  },
  {
    id: 'C007',
    name: '小林 由美',
    furigana: 'コバヤシ ユミ',
    phone: '090-2222-3333',
    phone2: '052-234-5678',
    email: 'kobayashi.y@example.com',
    email2: '',
    postalCode: '466-0834',
    address1: '愛知県名古屋市昭和区広路町',
    address2: '石坂2-15',
    salesRep: '鈴木',
    addedDate: '2025-01-16',
    store: '支店A',
    contractDate: '',
    deliveryStatus: '商談中',
    address: '愛知県名古屋市昭和区広路町石坂2-15',
    memo: '予算300万円以内',
    carType: '中古車',
    carModel: '',
    vinNumber: '',
    dealInfo: {
      vinNumber: '',
      carModel: '',
      maker: '',
      color: '',
      grade: '',
      year: '',
      mileage: '',
      modelType: '',
      salesPrice: 0,
      discount: 0,
      carType: '中古車',
      options: [],
      dealMemos: [
        { id: '8', date: '2025-01-16', content: 'ハイブリッド車希望' },
      ],
      statuses: {
        lineContact: { checked: true, date: '2025-01-16' },
        contract: { checked: false, date: '' },
        followUp1: { checked: false, date: '' },
        followUp2: { checked: false, date: '' },
        documents: { checked: false, date: '' },
        payment: { checked: false, date: '' },
        delivered: { checked: false, date: '' },
      },
      noFollowUp: false,
      paymentMethod: '',
      hasTradeIn: false,
      isInstantClose: false,
      dealChannel: 'phone',
    },
  },
  {
    id: 'C008',
    name: '加藤 誠',
    furigana: 'カトウ マコト',
    phone: '070-4444-5555',
    phone2: '',
    email: 'kato.m@example.com',
    email2: '',
    postalCode: '462-0844',
    address1: '愛知県名古屋市北区清水',
    address2: '4-17-1',
    salesRep: '佐藤',
    addedDate: '2025-01-18',
    store: '支店B',
    contractDate: '2025-01-22',
    deliveryStatus: '納車済み',
    address: '愛知県名古屋市北区清水4-17-1',
    memo: '即決',
    carType: '中古車',
    carModel: 'N-BOX',
    vinNumber: '33344455566677788',
    dealInfo: {
      vinNumber: '33344455566677788',
      carModel: 'N-BOX',
      maker: 'ホンダ',
      color: 'ブルー',
      grade: 'G',
      year: '2019',
      mileage: '48000',
      modelType: 'JF3',
      salesPrice: 780000,
      discount: 0,
      carType: '中古車',
      options: [],
      dealMemos: [
        { id: '9', date: '2025-01-18', content: '軽自動車で低予算' },
      ],
      statuses: {
        lineContact: { checked: true, date: '2025-01-18' },
        contract: { checked: true, date: '2025-01-22' },
        followUp1: { checked: true, date: '2025-01-23' },
        followUp2: { checked: false, date: '' },
        documents: { checked: true, date: '2025-01-24' },
        payment: { checked: true, date: '2025-01-25' },
        delivered: { checked: true, date: '2025-01-22' },
      },
      noFollowUp: false,
      paymentMethod: 'cash',
      hasTradeIn: false,
      isInstantClose: true,
      dealChannel: 'visit',
    },
  },
  {
    id: 'C009',
    name: '渡辺 真理子',
    furigana: 'ワタナベ マリコ',
    phone: '080-6666-7777',
    phone2: '',
    email: '',
    email2: '',
    postalCode: '458-0021',
    address1: '愛知県名古屋市緑区滝ノ水',
    address2: '2-101',
    salesRep: '田中',
    addedDate: '2025-01-20',
    store: '本店',
    contractDate: '',
    deliveryStatus: '商談中',
    address: '愛知県名古屋市緑区滝ノ水2-101',
    memo: 'オンライン問い合わせ',
    carType: '新車',
    carModel: '',
    vinNumber: '',
    dealInfo: {
      vinNumber: '',
      carModel: '',
      maker: '',
      color: '',
      grade: '',
      year: '',
      mileage: '',
      modelType: '',
      salesPrice: 0,
      discount: 0,
      carType: '新車',
      options: [],
      dealMemos: [
        { id: '10', date: '2025-01-20', content: 'SUV希望' },
      ],
      statuses: {
        lineContact: { checked: true, date: '2025-01-20' },
        contract: { checked: false, date: '' },
        followUp1: { checked: false, date: '' },
        followUp2: { checked: false, date: '' },
        documents: { checked: false, date: '' },
        payment: { checked: false, date: '' },
        delivered: { checked: false, date: '' },
      },
      noFollowUp: false,
      paymentMethod: '',
      hasTradeIn: false,
      isInstantClose: false,
      dealChannel: 'online',
    },
  },
  {
    id: 'C010',
    name: '山口 大輔',
    furigana: 'ヤマグチ ダイスケ',
    phone: '090-8888-9999',
    phone2: '052-345-6789',
    email: 'yamaguchi.d@example.com',
    email2: '',
    postalCode: '467-0806',
    address1: '愛知県名古屋市瑞穂区瑞穂通',
    address2: '3-14',
    salesRep: '山本',
    addedDate: '2025-01-22',
    store: '支店A',
    contractDate: '2025-01-28',
    deliveryStatus: '納車待ち',
    address: '愛知県名古屋市瑞穂区瑞穂通3-14',
    memo: '法人契約',
    carType: '中古車',
    carModel: 'ハリアー',
    vinNumber: '22233344455566677',
    dealInfo: {
      vinNumber: '22233344455566677',
      carModel: 'ハリアー',
      maker: 'トヨタ',
      color: '黒',
      grade: 'プレミアム',
      year: '2022',
      mileage: '15000',
      modelType: 'MXUA80',
      salesPrice: 2680000,
      discount: 0,
      carType: '中古車',
      options: [
        { id: 'opt6', category: 'ナビ', optionName: 'プレミアムナビ', amount: 80000 },
      ],
      dealMemos: [
        { id: '11', date: '2025-01-22', content: '社用車として購入' },
      ],
      statuses: {
        lineContact: { checked: true, date: '2025-01-22' },
        contract: { checked: true, date: '2025-01-28' },
        followUp1: { checked: false, date: '' },
        followUp2: { checked: false, date: '' },
        documents: { checked: false, date: '' },
        payment: { checked: false, date: '' },
        delivered: { checked: false, date: '' },
      },
      noFollowUp: false,
      paymentMethod: 'loan',
      hasTradeIn: false,
      isInstantClose: false,
      dealChannel: 'visit',
    },
  },
  {
    id: 'C011',
    name: '松本 康夫',
    furigana: 'マツモト ヤスオ',
    phone: '070-1111-2222',
    phone2: '',
    email: 'matsumoto@example.com',
    email2: '',
    postalCode: '454-0011',
    address1: '愛知県名古屋市中川区山王',
    address2: '1-5-8',
    salesRep: '高橋',
    addedDate: '2025-01-24',
    store: '本店',
    contractDate: '2025-01-30',
    deliveryStatus: '納車済み',
    address: '愛知県名古屋市中川区山王1-5-8',
    memo: '下取り車あり',
    carType: '中古車',
    carModel: 'フィット',
    vinNumber: '55566677788899900',
    dealInfo: {
      vinNumber: '55566677788899900',
      carModel: 'フィット',
      maker: 'ホンダ',
      color: '赤',
      grade: 'RS',
      year: '2020',
      mileage: '32000',
      modelType: 'GR3',
      salesPrice: 1180000,
      discount: 0,
      carType: '中古車',
      options: [],
      dealMemos: [
        { id: '12', date: '2025-01-24', content: '下取り見積もり依頼' },
      ],
      statuses: {
        lineContact: { checked: true, date: '2025-01-24' },
        contract: { checked: true, date: '2025-01-30' },
        followUp1: { checked: true, date: '2025-01-31' },
        followUp2: { checked: false, date: '' },
        documents: { checked: true, date: '2025-02-01' },
        payment: { checked: true, date: '2025-02-02' },
        delivered: { checked: true, date: '2025-01-30' },
      },
      noFollowUp: false,
      paymentMethod: 'loan',
      hasTradeIn: true,
      isInstantClose: false,
      dealChannel: 'visit',
    },
  },
  {
    id: 'C012',
    name: '井上 美香',
    furigana: 'イノウエ ミカ',
    phone: '080-3333-4444',
    phone2: '',
    email: 'inoue.m@example.com',
    email2: '',
    postalCode: '465-0093',
    address1: '愛知県名古屋市名東区一社',
    address2: '2-88',
    salesRep: '鈴木',
    addedDate: '2025-01-26',
    store: '支店A',
    contractDate: '',
    deliveryStatus: '商談中',
    address: '愛知県名古屋市名東区一社2-88',
    memo: '色にこだわり',
    carType: '中古車',
    carModel: '',
    vinNumber: '',
    dealInfo: {
      vinNumber: '',
      carModel: '',
      maker: '',
      color: '',
      grade: '',
      year: '',
      mileage: '',
      modelType: '',
      salesPrice: 0,
      discount: 0,
      carType: '中古車',
      options: [],
      dealMemos: [
        { id: '13', date: '2025-01-26', content: '白または銀色希望' },
      ],
      statuses: {
        lineContact: { checked: false, date: '' },
        contract: { checked: false, date: '' },
        followUp1: { checked: false, date: '' },
        followUp2: { checked: false, date: '' },
        documents: { checked: false, date: '' },
        payment: { checked: false, date: '' },
        delivered: { checked: false, date: '' },
      },
      noFollowUp: false,
      paymentMethod: '',
      hasTradeIn: false,
      isInstantClose: false,
      dealChannel: 'online',
    },
  },
  {
    id: 'C013',
    name: '木村 隆',
    furigana: 'キムラ タカシ',
    phone: '090-5555-6666',
    phone2: '052-456-7890',
    email: 'kimura.t@example.com',
    email2: '',
    postalCode: '463-0011',
    address1: '愛知県名古屋市守山区小幡',
    address2: '5-8-28',
    salesRep: '佐藤',
    addedDate: '2025-01-28',
    store: '支店B',
    contractDate: '2025-02-02',
    deliveryStatus: '納車済み',
    address: '愛知県名古屋市守山区小幡5-8-28',
    memo: '紹介案件',
    carType: '中古車',
    carModel: 'ノート',
    vinNumber: '44455566677788899',
    dealInfo: {
      vinNumber: '44455566677788899',
      carModel: 'ノート',
      maker: '日産',
      color: '白',
      grade: 'e-POWER X',
      year: '2021',
      mileage: '25000',
      modelType: 'E13',
      salesPrice: 1680000,
      discount: 0,
      carType: '中古車',
      options: [],
      dealMemos: [
        { id: '14', date: '2025-01-28', content: '友人からの紹介' },
      ],
      statuses: {
        lineContact: { checked: true, date: '2025-01-28' },
        contract: { checked: true, date: '2025-02-02' },
        followUp1: { checked: true, date: '2025-02-03' },
        followUp2: { checked: false, date: '' },
        documents: { checked: true, date: '2025-02-04' },
        payment: { checked: true, date: '2025-02-05' },
        delivered: { checked: true, date: '2025-02-02' },
      },
      noFollowUp: false,
      paymentMethod: 'cash',
      hasTradeIn: false,
      isInstantClose: false,
      dealChannel: 'visit',
    },
  },
  {
    id: 'C014',
    name: '林 裕子',
    furigana: 'ハヤシ ユウコ',
    phone: '080-7777-8888',
    phone2: '',
    email: '',
    email2: '',
    postalCode: '456-0002',
    address1: '愛知県名古屋市熱田区金山町',
    address2: '1-16-30',
    salesRep: '田中',
    addedDate: '2025-01-30',
    store: '本店',
    contractDate: '',
    deliveryStatus: '商談中',
    address: '愛知県名古屋市熱田区金山町1-16-30',
    memo: '初回来店',
    carType: '新車',
    carModel: '',
    vinNumber: '',
    dealInfo: {
      vinNumber: '',
      carModel: '',
      maker: '',
      color: '',
      grade: '',
      year: '',
      mileage: '',
      modelType: '',
      salesPrice: 0,
      discount: 0,
      carType: '新車',
      options: [],
      dealMemos: [
        { id: '15', date: '2025-01-30', content: 'コンパクトカー希望' },
      ],
      statuses: {
        lineContact: { checked: true, date: '2025-01-30' },
        contract: { checked: false, date: '' },
        followUp1: { checked: false, date: '' },
        followUp2: { checked: false, date: '' },
        documents: { checked: false, date: '' },
        payment: { checked: false, date: '' },
        delivered: { checked: false, date: '' },
      },
      noFollowUp: false,
      paymentMethod: '',
      hasTradeIn: false,
      isInstantClose: false,
      dealChannel: 'phone',
    },
  },
  {
    id: 'C015',
    name: '斎藤 英二',
    furigana: 'サイトウ エイジ',
    phone: '090-9999-0000',
    phone2: '',
    email: 'saito.e@example.com',
    email2: 'saito.work@example.com',
    postalCode: '457-0071',
    address1: '愛知県名古屋市南区千竈通',
    address2: '7-13-1',
    salesRep: '山本',
    addedDate: '2025-02-01',
    store: '支店A',
    contractDate: '2025-02-08',
    deliveryStatus: '納車待ち',
    address: '愛知県名古屋市南区千竈通7-13-1',
    memo: 'オンライン商談',
    carType: '中古車',
    carModel: 'ヤリス',
    vinNumber: '66677788899900011',
    dealInfo: {
      vinNumber: '66677788899900011',
      carModel: 'ヤリス',
      maker: 'トヨタ',
      color: 'グレー',
      grade: 'Z',
      year: '2021',
      mileage: '18000',
      modelType: 'MXPA10',
      salesPrice: 1480000,
      discount: 0,
      carType: '中古車',
      options: [
        { id: 'opt7', category: '内装', optionName: 'シートカバー', amount: 18000 },
        { id: 'opt8', category: 'ナビ', optionName: 'カーナビ', amount: 35000 },
      ],
      dealMemos: [
        { id: '16', date: '2025-02-01', content: 'Zoom商談実施' },
      ],
      statuses: {
        lineContact: { checked: true, date: '2025-02-01' },
        contract: { checked: true, date: '2025-02-08' },
        followUp1: { checked: false, date: '' },
        followUp2: { checked: false, date: '' },
        documents: { checked: false, date: '' },
        payment: { checked: false, date: '' },
        delivered: { checked: false, date: '' },
      },
      noFollowUp: false,
      paymentMethod: 'loan',
      hasTradeIn: false,
      isInstantClose: true,
      dealChannel: 'visit',
    },
  },
  {
    id: 'C016',
    name: '森田 達也',
    furigana: 'モリタ タツヤ',
    phone: '070-2222-3333',
    phone2: '052-567-8901',
    email: 'morita.t@example.com',
    email2: '',
    postalCode: '455-0803',
    address1: '愛知県名古屋市港区港明',
    address2: '2-3-2',
    salesRep: '高橋',
    addedDate: '2025-02-03',
    store: '本店',
    contractDate: '2025-02-10',
    deliveryStatus: '納車済み',
    address: '愛知県名古屋市港区港明2-3-2',
    memo: 'リース希望だったが購入に',
    carType: '中古車',
    carModel: 'カローラ',
    vinNumber: '88899900011122233',
    dealInfo: {
      vinNumber: '88899900011122233',
      carModel: 'カローラ',
      maker: 'トヨタ',
      color: 'シルバー',
      grade: 'G-X',
      year: '2018',
      mileage: '58000',
      modelType: 'NRE210',
      salesPrice: 880000,
      discount: 0,
      carType: '中古車',
      options: [],
      dealMemos: [
        { id: '17', date: '2025-02-03', content: '商用車として利用予定' },
      ],
      statuses: {
        lineContact: { checked: true, date: '2025-02-03' },
        contract: { checked: true, date: '2025-02-10' },
        followUp1: { checked: true, date: '2025-02-11' },
        followUp2: { checked: false, date: '' },
        documents: { checked: true, date: '2025-02-12' },
        payment: { checked: true, date: '2025-02-13' },
        delivered: { checked: true, date: '2025-02-10' },
      },
      noFollowUp: false,
      paymentMethod: 'cash',
      hasTradeIn: true,
      isInstantClose: false,
      dealChannel: 'phone',
    },
  },
  {
    id: 'C017',
    name: '清水 京子',
    furigana: 'シミズ キョウコ',
    phone: '080-4444-5555',
    phone2: '',
    email: 'shimizu.k@example.com',
    email2: '',
    postalCode: '468-0014',
    address1: '愛知県名古屋市天白区中平',
    address2: '5-613',
    salesRep: '鈴木',
    addedDate: '2025-02-05',
    store: '支店B',
    contractDate: '',
    deliveryStatus: '商談中',
    address: '愛知県名古屋市天白区中平5-613',
    memo: '女性目線で相談',
    carType: '中古車',
    carModel: '',
    vinNumber: '',
    dealInfo: {
      vinNumber: '',
      carModel: '',
      maker: '',
      color: '',
      grade: '',
      year: '',
      mileage: '',
      modelType: '',
      salesPrice: 0,
      discount: 0,
      carType: '中古車',
      options: [],
      dealMemos: [
        { id: '18', date: '2025-02-05', content: '可愛いデザイン希望' },
      ],
      statuses: {
        lineContact: { checked: true, date: '2025-02-05' },
        contract: { checked: false, date: '' },
        followUp1: { checked: false, date: '' },
        followUp2: { checked: false, date: '' },
        documents: { checked: false, date: '' },
        payment: { checked: false, date: '' },
        delivered: { checked: false, date: '' },
      },
      noFollowUp: false,
      paymentMethod: '',
      hasTradeIn: false,
      isInstantClose: false,
      dealChannel: 'online',
    },
  },
  {
    id: 'C018',
    name: '橋本 信一',
    furigana: 'ハシモト シンイチ',
    phone: '090-6666-7777',
    phone2: '',
    email: 'hashimoto.s@example.com',
    email2: '',
    postalCode: '461-0004',
    address1: '愛知県名古屋市東区葵',
    address2: '3-21-19',
    salesRep: '佐藤',
    addedDate: '2025-02-07',
    store: '支店A',
    contractDate: '2025-02-12',
    deliveryStatus: '納車済み',
    address: '愛知県名古屋市東区葵3-21-19',
    memo: '2台目購入',
    carType: '新車',
    carModel: 'アルファード',
    vinNumber: '77788899900011122',
    dealInfo: {
      vinNumber: '77788899900011122',
      carModel: 'アルファード',
      maker: 'トヨタ',
      color: '白パール',
      grade: 'S Cパッケージ',
      year: '2021',
      mileage: '22000',
      modelType: 'AGH30W',
      salesPrice: 3280000,
      discount: 0,
      carType: '新車',
      options: [
        { id: 'opt9', category: 'ナビ', optionName: 'プレミアムナビ', amount: 100000 },
        { id: 'opt10', category: '内装', optionName: 'レザーシート', amount: 150000 },
      ],
      dealMemos: [
        { id: '19', date: '2025-02-07', content: 'リピーター、高級志向' },
      ],
      statuses: {
        lineContact: { checked: true, date: '2025-02-07' },
        contract: { checked: true, date: '2025-02-12' },
        followUp1: { checked: true, date: '2025-02-13' },
        followUp2: { checked: false, date: '' },
        documents: { checked: true, date: '2025-02-14' },
        payment: { checked: true, date: '2025-02-15' },
        delivered: { checked: true, date: '2025-02-12' },
      },
      noFollowUp: false,
      paymentMethod: 'loan',
      hasTradeIn: true,
      isInstantClose: false,
      dealChannel: 'visit',
    },
  },
  {
    id: 'C019',
    name: '石川 美咲',
    furigana: 'イシカワ ミサキ',
    phone: '070-8888-9999',
    phone2: '',
    email: '',
    email2: '',
    postalCode: '452-0802',
    address1: '愛知県名古屋市西区比良',
    address2: '2-140',
    salesRep: '田中',
    addedDate: '2025-02-09',
    store: '本店',
    contractDate: '',
    deliveryStatus: '商談中',
    address: '愛知県名古屋市西区比良2-140',
    memo: '初めての車購入',
    carType: '中古車',
    carModel: '',
    vinNumber: '',
    dealInfo: {
      vinNumber: '',
      carModel: '',
      maker: '',
      color: '',
      grade: '',
      year: '',
      mileage: '',
      modelType: '',
      salesPrice: 0,
      discount: 0,
      carType: '中古車',
      options: [],
      dealMemos: [
        { id: '20', date: '2025-02-09', content: '予算は100万円以下' },
      ],
      statuses: {
        lineContact: { checked: false, date: '' },
        contract: { checked: false, date: '' },
        followUp1: { checked: false, date: '' },
        followUp2: { checked: false, date: '' },
        documents: { checked: false, date: '' },
        payment: { checked: false, date: '' },
        delivered: { checked: false, date: '' },
      },
      noFollowUp: false,
      paymentMethod: '',
      hasTradeIn: false,
      isInstantClose: false,
      dealChannel: 'online',
    },
  },
  {
    id: 'C020',
    name: '長谷川 浩二',
    furigana: 'ハセガワ コウジ',
    phone: '080-1111-2222',
    phone2: '052-678-9012',
    email: 'hasegawa.k@example.com',
    email2: '',
    postalCode: '464-0075',
    address1: '愛知県名古屋市千種区内山',
    address2: '3-10-3',
    salesRep: '山本',
    addedDate: '2025-02-11',
    store: '支店B',
    contractDate: '',
    deliveryStatus: '商談中',
    address: '愛知県名古屋市千種区内山3-10-3',
    memo: '現金一括払い希望',
    carType: '中古車',
    carModel: 'プリウス',
    vinNumber: '12345678901234567',
    dealInfo: {
      vinNumber: '12345678901234567',
      carModel: 'プリウス',
      maker: 'トヨタ',
      color: '白',
      grade: 'S',
      year: '2018',
      mileage: '45000',
      modelType: 'ZVW30',
      salesPrice: 0,
      discount: 0,
      carType: '中古車',
      options: [],
      dealMemos: [
        { id: '21', date: '2025-02-11', content: '燃費重視' },
      ],
      statuses: {
        lineContact: { checked: true, date: '2025-02-11' },
        contract: { checked: false, date: '' },
        followUp1: { checked: false, date: '' },
        followUp2: { checked: false, date: '' },
        documents: { checked: false, date: '' },
        payment: { checked: false, date: '' },
        delivered: { checked: false, date: '' },
      },
      noFollowUp: false,
      paymentMethod: '',
      hasTradeIn: false,
      isInstantClose: false,
      dealChannel: 'phone',
    },
  },
]

// ============ 在庫管理用の型定義 ============

export interface LegalFeeItem {
  id: string
  category: string
  amount: number
}

export interface OptionItem {
  id: string
  category: string
  optionName: string
  amount: number
}

export interface PurchaseInfo {
  purchaseDate: string
  purchaseType: string // オークション、下取、その他
  supplier: string
  expectedArrivalDate: string
  arrivalDate: string
  notifyOnDelay: boolean
  purchaseManager: string
  store: string
  depositStatus: string
  depositAmount: number
  purchasePrice: number
  legalFees: LegalFeeItem[]
  options: OptionItem[]
  autoTax: number
  autoTaxEnv: number
  weightTax: number
  compulsoryInsurance: number
  voluntaryInsurance: number
  totalAmount: number
}

export interface VehicleInfo {
  vinNumber: string
  carModel: string
  maker: string
  color: string
  grade: string
  year: string
  mileage: string
  modelType: string
  referencePrice: number
}

export interface SalesInfo {
  displayLocation: string
  salesPrice: number
  onlinePosted: boolean
  notes: string
}

export type InventoryStatus = 'available' | 'negotiating' | 'sold' | 'cancelled'

export interface InventoryItem {
  id: string
  purchaseInfo: PurchaseInfo
  vehicleInfo: VehicleInfo
  salesInfo: SalesInfo
  status: InventoryStatus
  customerId: string | null
  reservedDate: string
  soldDate: string
}

// ============ 在庫管理用のダミーデータ ============

export const DUMMY_INVENTORY: InventoryItem[] = [
  {
    id: 'INV001',
    purchaseInfo: {
      purchaseDate: '2025-01-10',
      purchaseType: 'オークション',
      supplier: 'AA名古屋会場',
      expectedArrivalDate: '2025-01-14',
      arrivalDate: '2025-01-15',
      notifyOnDelay: true,
      purchaseManager: '高橋',
      store: '本店',
      depositStatus: '預託済',
      depositAmount: 50000,
      purchasePrice: 1000000,
      legalFees: [
        { id: 'lf1', category: '自動車税', amount: 39500 },
        { id: 'lf2', category: '重量税', amount: 24600 },
      ],
      options: [
        { id: 'opt1', category: '内装', optionName: 'フロアマット', amount: 15000 },
        { id: 'opt2', category: '外装', optionName: 'ドアバイザー', amount: 12000 },
      ],
      autoTax: 39500,
      autoTaxEnv: 0,
      weightTax: 24600,
      compulsoryInsurance: 25830,
      voluntaryInsurance: 0,
      totalAmount: 1150000,
    },
    vehicleInfo: {
      vinNumber: '12345678901234567',
      carModel: 'プリウス',
      maker: 'トヨタ',
      color: '白',
      grade: 'S',
      year: '2018',
      mileage: '45000',
      modelType: 'ZVW30',
      referencePrice: 1200000,
    },
    salesInfo: {
      displayLocation: '本店1F',
      salesPrice: 1380000,
      onlinePosted: true,
      notes: '人気車種、状態良好',
    },
    status: 'negotiating',
    customerId: 'C001',
    reservedDate: '2025-01-15',
    soldDate: '',
  },
  {
    id: 'INV002',
    purchaseInfo: {
      purchaseDate: '2025-01-08',
      purchaseType: '下取',
      supplier: '顧客：山田太郎様',
      expectedArrivalDate: '2025-01-10',
      arrivalDate: '2025-01-10',
      notifyOnDelay: false,
      purchaseManager: '鈴木',
      store: '本店',
      depositStatus: '不要',
      depositAmount: 0,
      purchasePrice: 650000,
      legalFees: [
        { id: 'lf3', category: '自動車税', amount: 29500 },
      ],
      options: [],
      autoTax: 29500,
      autoTaxEnv: 0,
      weightTax: 16400,
      compulsoryInsurance: 20010,
      voluntaryInsurance: 0,
      totalAmount: 715910,
    },
    vehicleInfo: {
      vinNumber: '98765432109876543',
      carModel: 'アクア',
      maker: 'トヨタ',
      color: '黒',
      grade: 'G',
      year: '2020',
      mileage: '28000',
      modelType: 'NHP10',
      referencePrice: 850000,
    },
    salesInfo: {
      displayLocation: '本店2F',
      salesPrice: 980000,
      onlinePosted: true,
      notes: 'ワンオーナー、禁煙車',
    },
    status: 'sold',
    customerId: 'C002',
    reservedDate: '2025-01-08',
    soldDate: '2025-01-20',
  },
  {
    id: 'INV003',
    purchaseInfo: {
      purchaseDate: '2024-12-20',
      purchaseType: 'オークション',
      supplier: 'USS東京',
      expectedArrivalDate: '2024-12-25',
      arrivalDate: '2024-12-26',
      notifyOnDelay: true,
      purchaseManager: '佐藤',
      store: '支店A',
      depositStatus: '預託済',
      depositAmount: 80000,
      purchasePrice: 1500000,
      legalFees: [
        { id: 'lf4', category: '自動車税', amount: 51000 },
        { id: 'lf5', category: '重量税', amount: 32800 },
      ],
      options: [
        { id: 'opt3', category: 'ナビ', optionName: '社外ナビ取付', amount: 80000 },
        { id: 'opt4', category: 'その他', optionName: 'ETC', amount: 15000 },
      ],
      autoTax: 51000,
      autoTaxEnv: 0,
      weightTax: 32800,
      compulsoryInsurance: 25830,
      voluntaryInsurance: 0,
      totalAmount: 1704630,
    },
    vehicleInfo: {
      vinNumber: '11122233344455566',
      carModel: 'ヴォクシー',
      maker: 'トヨタ',
      color: 'シルバー',
      grade: 'ZS',
      year: '2019',
      mileage: '35000',
      modelType: 'ZRR80',
      referencePrice: 1800000,
    },
    salesInfo: {
      displayLocation: '支店A 1F',
      salesPrice: 2180000,
      onlinePosted: true,
      notes: '7人乗り、ファミリーに人気',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV004',
    purchaseInfo: {
      purchaseDate: '2025-01-05',
      purchaseType: 'オークション',
      supplier: 'JU大阪',
      expectedArrivalDate: '2025-01-12',
      arrivalDate: '2025-01-12',
      notifyOnDelay: true,
      purchaseManager: '田中',
      store: '支店B',
      depositStatus: '預託済',
      depositAmount: 60000,
      purchasePrice: 2200000,
      legalFees: [
        { id: 'lf6', category: '自動車税', amount: 66500 },
        { id: 'lf7', category: '重量税', amount: 49200 },
      ],
      options: [
        { id: 'opt5', category: '外装', optionName: 'コーティング', amount: 50000 },
      ],
      autoTax: 66500,
      autoTaxEnv: 0,
      weightTax: 49200,
      compulsoryInsurance: 25830,
      voluntaryInsurance: 0,
      totalAmount: 2441530,
    },
    vehicleInfo: {
      vinNumber: '77788899900011122',
      carModel: 'アルファード',
      maker: 'トヨタ',
      color: '白パール',
      grade: 'S Cパッケージ',
      year: '2021',
      mileage: '22000',
      modelType: 'AGH30W',
      referencePrice: 2800000,
    },
    salesInfo: {
      displayLocation: '支店B 1F',
      salesPrice: 3280000,
      onlinePosted: true,
      notes: '高級ミニバン、上質な内装',
    },
    status: 'negotiating',
    customerId: 'C004',
    reservedDate: '2025-01-12',
    soldDate: '',
  },
  {
    id: 'INV005',
    purchaseInfo: {
      purchaseDate: '2025-01-12',
      purchaseType: '下取',
      supplier: '顧客：鈴木次郎様',
      expectedArrivalDate: '2025-01-15',
      arrivalDate: '2025-01-16',
      notifyOnDelay: false,
      purchaseManager: '高橋',
      store: '本店',
      depositStatus: '不要',
      depositAmount: 0,
      purchasePrice: 450000,
      legalFees: [
        { id: 'lf8', category: '自動車税', amount: 25000 },
      ],
      options: [],
      autoTax: 25000,
      autoTaxEnv: 0,
      weightTax: 12300,
      compulsoryInsurance: 17540,
      voluntaryInsurance: 0,
      totalAmount: 504840,
    },
    vehicleInfo: {
      vinNumber: '33344455566677788',
      carModel: 'N-BOX',
      maker: 'ホンダ',
      color: 'ブルー',
      grade: 'G',
      year: '2019',
      mileage: '48000',
      modelType: 'JF3',
      referencePrice: 600000,
    },
    salesInfo: {
      displayLocation: '本店1F',
      salesPrice: 780000,
      onlinePosted: true,
      notes: '軽自動車、燃費良好',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV006',
    purchaseInfo: {
      purchaseDate: '2024-12-28',
      purchaseType: 'オークション',
      supplier: 'TAA横浜',
      expectedArrivalDate: '2025-01-05',
      arrivalDate: '2025-01-06',
      notifyOnDelay: true,
      purchaseManager: '鈴木',
      store: '支店A',
      depositStatus: '預託済',
      depositAmount: 45000,
      purchasePrice: 850000,
      legalFees: [
        { id: 'lf9', category: '自動車税', amount: 34500 },
        { id: 'lf10', category: '重量税', amount: 24600 },
      ],
      options: [
        { id: 'opt6', category: '内装', optionName: 'シートカバー', amount: 18000 },
      ],
      autoTax: 34500,
      autoTaxEnv: 0,
      weightTax: 24600,
      compulsoryInsurance: 25830,
      voluntaryInsurance: 0,
      totalAmount: 952930,
    },
    vehicleInfo: {
      vinNumber: '55566677788899900',
      carModel: 'フィット',
      maker: 'ホンダ',
      color: '赤',
      grade: 'RS',
      year: '2020',
      mileage: '32000',
      modelType: 'GR3',
      referencePrice: 1000000,
    },
    salesInfo: {
      displayLocation: '支店A 2F',
      salesPrice: 1180000,
      onlinePosted: true,
      notes: 'スポーツグレード',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV007',
    purchaseInfo: {
      purchaseDate: '2025-01-14',
      purchaseType: 'オークション',
      supplier: 'AA名古屋会場',
      expectedArrivalDate: '2025-01-18',
      arrivalDate: '',
      notifyOnDelay: true,
      purchaseManager: '佐藤',
      store: '本店',
      depositStatus: '預託済',
      depositAmount: 70000,
      purchasePrice: 1800000,
      legalFees: [
        { id: 'lf11', category: '自動車税', amount: 45000 },
      ],
      options: [],
      autoTax: 45000,
      autoTaxEnv: 0,
      weightTax: 32800,
      compulsoryInsurance: 25830,
      voluntaryInsurance: 0,
      totalAmount: 1903630,
    },
    vehicleInfo: {
      vinNumber: '22233344455566677',
      carModel: 'ハリアー',
      maker: 'トヨタ',
      color: '黒',
      grade: 'プレミアム',
      year: '2022',
      mileage: '15000',
      modelType: 'MXUA80',
      referencePrice: 2300000,
    },
    salesInfo: {
      displayLocation: '入庫待ち',
      salesPrice: 2680000,
      onlinePosted: false,
      notes: '入庫次第展示予定',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV008',
    purchaseInfo: {
      purchaseDate: '2024-12-15',
      purchaseType: '下取',
      supplier: '顧客：田中一郎様',
      expectedArrivalDate: '2024-12-18',
      arrivalDate: '2024-12-18',
      notifyOnDelay: false,
      purchaseManager: '田中',
      store: '支店B',
      depositStatus: '不要',
      depositAmount: 0,
      purchasePrice: 550000,
      legalFees: [
        { id: 'lf12', category: '自動車税', amount: 30000 },
      ],
      options: [
        { id: 'opt7', category: 'メンテナンス', optionName: 'エンジンオイル交換', amount: 5000 },
      ],
      autoTax: 30000,
      autoTaxEnv: 0,
      weightTax: 16400,
      compulsoryInsurance: 20010,
      voluntaryInsurance: 0,
      totalAmount: 621410,
    },
    vehicleInfo: {
      vinNumber: '88899900011122233',
      carModel: 'カローラ',
      maker: 'トヨタ',
      color: 'シルバー',
      grade: 'G-X',
      year: '2018',
      mileage: '58000',
      modelType: 'NRE210',
      referencePrice: 750000,
    },
    salesInfo: {
      displayLocation: '支店B 2F',
      salesPrice: 880000,
      onlinePosted: true,
      notes: '実用的なセダン',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV009',
    purchaseInfo: {
      purchaseDate: '2025-01-03',
      purchaseType: 'オークション',
      supplier: 'USS東京',
      expectedArrivalDate: '2025-01-08',
      arrivalDate: '2025-01-09',
      notifyOnDelay: true,
      purchaseManager: '高橋',
      store: '本店',
      depositStatus: '預託済',
      depositAmount: 55000,
      purchasePrice: 1200000,
      legalFees: [
        { id: 'lf13', category: '自動車税', amount: 39500 },
        { id: 'lf14', category: '重量税', amount: 24600 },
      ],
      options: [
        { id: 'opt8', category: 'ナビ', optionName: 'カーナビ更新', amount: 20000 },
        { id: 'opt9', category: '外装', optionName: 'ヘッドライト磨き', amount: 8000 },
      ],
      autoTax: 39500,
      autoTaxEnv: 0,
      weightTax: 24600,
      compulsoryInsurance: 25830,
      voluntaryInsurance: 0,
      totalAmount: 1317930,
    },
    vehicleInfo: {
      vinNumber: '44455566677788899',
      carModel: 'ノート',
      maker: '日産',
      color: '白',
      grade: 'e-POWER X',
      year: '2021',
      mileage: '25000',
      modelType: 'E13',
      referencePrice: 1400000,
    },
    salesInfo: {
      displayLocation: '本店2F',
      salesPrice: 1680000,
      onlinePosted: true,
      notes: 'e-POWER搭載、低燃費',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV010',
    purchaseInfo: {
      purchaseDate: '2025-01-11',
      purchaseType: 'オークション',
      supplier: 'JU大阪',
      expectedArrivalDate: '2025-01-16',
      arrivalDate: '2025-01-17',
      notifyOnDelay: true,
      purchaseManager: '鈴木',
      store: '支店A',
      depositStatus: '預託済',
      depositAmount: 40000,
      purchasePrice: 950000,
      legalFees: [
        { id: 'lf15', category: '自動車税', amount: 36000 },
      ],
      options: [],
      autoTax: 36000,
      autoTaxEnv: 0,
      weightTax: 20500,
      compulsoryInsurance: 20010,
      voluntaryInsurance: 0,
      totalAmount: 1026510,
    },
    vehicleInfo: {
      vinNumber: '66677788899900011',
      carModel: 'ヤリス',
      maker: 'トヨタ',
      color: 'グレー',
      grade: 'Z',
      year: '2021',
      mileage: '18000',
      modelType: 'MXPA10',
      referencePrice: 1150000,
    },
    salesInfo: {
      displayLocation: '支店A 1F',
      salesPrice: 1480000,
      onlinePosted: true,
      notes: 'コンパクトカー、新しめ',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV011',
    purchaseInfo: {
      purchaseDate: '2025-01-15',
      purchaseType: 'オークション',
      supplier: 'TAA横浜',
      expectedArrivalDate: '2025-01-20',
      arrivalDate: '2025-01-21',
      notifyOnDelay: true,
      purchaseManager: '高橋',
      store: '本店',
      depositStatus: '預託済',
      depositAmount: 45000,
      purchasePrice: 900000,
      legalFees: [
        { id: 'lf16', category: '自動車税', amount: 34500 },
        { id: 'lf17', category: '重量税', amount: 20500 },
      ],
      options: [],
      autoTax: 34500,
      autoTaxEnv: 0,
      weightTax: 20500,
      compulsoryInsurance: 20010,
      voluntaryInsurance: 0,
      totalAmount: 975010,
    },
    vehicleInfo: {
      vinNumber: '11223344556677889',
      carModel: 'タント',
      maker: 'ダイハツ',
      color: 'ピンク',
      grade: 'X',
      year: '2020',
      mileage: '35000',
      modelType: 'LA650S',
      referencePrice: 950000,
    },
    salesInfo: {
      displayLocation: '本店1F',
      salesPrice: 1150000,
      onlinePosted: true,
      notes: '人気の軽自動車',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV012',
    purchaseInfo: {
      purchaseDate: '2025-01-16',
      purchaseType: '下取',
      supplier: '顧客：清水京子様',
      expectedArrivalDate: '2025-01-18',
      arrivalDate: '2025-01-18',
      notifyOnDelay: false,
      purchaseManager: '田中',
      store: '支店B',
      depositStatus: '不要',
      depositAmount: 0,
      purchasePrice: 550000,
      legalFees: [],
      options: [],
      autoTax: 29500,
      autoTaxEnv: 0,
      weightTax: 16400,
      compulsoryInsurance: 20010,
      voluntaryInsurance: 0,
      totalAmount: 615910,
    },
    vehicleInfo: {
      vinNumber: '99988877766655544',
      carModel: 'ムーヴ',
      maker: 'ダイハツ',
      color: 'ライトブルー',
      grade: 'L',
      year: '2017',
      mileage: '62000',
      modelType: 'LA150S',
      referencePrice: 650000,
    },
    salesInfo: {
      displayLocation: '支店B 2F',
      salesPrice: 850000,
      onlinePosted: true,
      notes: '経済的な軽自動車',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV013',
    purchaseInfo: {
      purchaseDate: '2025-01-13',
      purchaseType: 'オークション',
      supplier: 'USS東京',
      expectedArrivalDate: '2025-01-18',
      arrivalDate: '2025-01-19',
      notifyOnDelay: true,
      purchaseManager: '鈴木',
      store: '支店A',
      depositStatus: '預託済',
      depositAmount: 55000,
      purchasePrice: 1300000,
      legalFees: [
        { id: 'lf18', category: '自動車税', amount: 39500 },
        { id: 'lf19', category: '重量税', amount: 24600 },
      ],
      options: [
        { id: 'opt10', category: 'ナビ', optionName: 'カーナビ', amount: 35000 },
      ],
      autoTax: 39500,
      autoTaxEnv: 0,
      weightTax: 24600,
      compulsoryInsurance: 25830,
      voluntaryInsurance: 0,
      totalAmount: 1424930,
    },
    vehicleInfo: {
      vinNumber: '22334455667788990',
      carModel: 'セレナ',
      maker: '日産',
      color: 'パールホワイト',
      grade: 'ハイウェイスター',
      year: '2020',
      mileage: '42000',
      modelType: 'C27',
      referencePrice: 1600000,
    },
    salesInfo: {
      displayLocation: '支店A 1F',
      salesPrice: 1980000,
      onlinePosted: true,
      notes: 'ファミリーに人気',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV014',
    purchaseInfo: {
      purchaseDate: '2025-01-14',
      purchaseType: 'オークション',
      supplier: 'JU大阪',
      expectedArrivalDate: '2025-01-19',
      arrivalDate: '2025-01-20',
      notifyOnDelay: false,
      purchaseManager: '佐藤',
      store: '本店',
      depositStatus: '預託済',
      depositAmount: 50000,
      purchasePrice: 1100000,
      legalFees: [
        { id: 'lf20', category: '自動車税', amount: 39500 },
      ],
      options: [],
      autoTax: 39500,
      autoTaxEnv: 0,
      weightTax: 24600,
      compulsoryInsurance: 25830,
      voluntaryInsurance: 0,
      totalAmount: 1189930,
    },
    vehicleInfo: {
      vinNumber: '33445566778899001',
      carModel: 'C-HR',
      maker: 'トヨタ',
      color: 'メタルストリームメタリック',
      grade: 'G',
      year: '2019',
      mileage: '38000',
      modelType: 'NGX50',
      referencePrice: 1350000,
    },
    salesInfo: {
      displayLocation: '本店2F',
      salesPrice: 1680000,
      onlinePosted: true,
      notes: 'スタイリッシュSUV',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV015',
    purchaseInfo: {
      purchaseDate: '2025-01-17',
      purchaseType: '下取',
      supplier: '顧客：林裕子様',
      expectedArrivalDate: '2025-01-20',
      arrivalDate: '2025-01-20',
      notifyOnDelay: false,
      purchaseManager: '高橋',
      store: '本店',
      depositStatus: '不要',
      depositAmount: 0,
      purchasePrice: 750000,
      legalFees: [],
      options: [],
      autoTax: 34500,
      autoTaxEnv: 0,
      weightTax: 20500,
      compulsoryInsurance: 20010,
      voluntaryInsurance: 0,
      totalAmount: 825010,
    },
    vehicleInfo: {
      vinNumber: '44556677889900112',
      carModel: 'スペイド',
      maker: 'トヨタ',
      color: 'シルバー',
      grade: 'Y',
      year: '2018',
      mileage: '48000',
      modelType: 'NSP141',
      referencePrice: 850000,
    },
    salesInfo: {
      displayLocation: '本店2F',
      salesPrice: 1080000,
      onlinePosted: false,
      notes: '使い勝手の良いコンパクト',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV016',
    purchaseInfo: {
      purchaseDate: '2025-01-18',
      purchaseType: 'オークション',
      supplier: 'AA名古屋会場',
      expectedArrivalDate: '2025-01-23',
      arrivalDate: '',
      notifyOnDelay: true,
      purchaseManager: '田中',
      store: '支店A',
      depositStatus: '預託済',
      depositAmount: 65000,
      purchasePrice: 1750000,
      legalFees: [],
      options: [],
      autoTax: 45000,
      autoTaxEnv: 0,
      weightTax: 32800,
      compulsoryInsurance: 25830,
      voluntaryInsurance: 0,
      totalAmount: 1853630,
    },
    vehicleInfo: {
      vinNumber: '55667788990011223',
      carModel: 'エクストレイル',
      maker: '日産',
      color: 'ダイヤモンドブラック',
      grade: '20Xi',
      year: '2021',
      mileage: '28000',
      modelType: 'T32',
      referencePrice: 2100000,
    },
    salesInfo: {
      displayLocation: '入庫待ち',
      salesPrice: 2480000,
      onlinePosted: false,
      notes: '入庫次第展示予定',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV017',
    purchaseInfo: {
      purchaseDate: '2025-01-12',
      purchaseType: 'オークション',
      supplier: 'USS東京',
      expectedArrivalDate: '2025-01-17',
      arrivalDate: '2025-01-17',
      notifyOnDelay: true,
      purchaseManager: '鈴木',
      store: '本店',
      depositStatus: '預託済',
      depositAmount: 40000,
      purchasePrice: 820000,
      legalFees: [
        { id: 'lf21', category: '自動車税', amount: 29500 },
      ],
      options: [],
      autoTax: 29500,
      autoTaxEnv: 0,
      weightTax: 16400,
      compulsoryInsurance: 20010,
      voluntaryInsurance: 0,
      totalAmount: 885910,
    },
    vehicleInfo: {
      vinNumber: '66778899001122334',
      carModel: 'マーチ',
      maker: '日産',
      color: 'ピュアホワイトパール',
      grade: 'S',
      year: '2019',
      mileage: '41000',
      modelType: 'K13',
      referencePrice: 950000,
    },
    salesInfo: {
      displayLocation: '本店1F',
      salesPrice: 1180000,
      onlinePosted: true,
      notes: 'コンパクトで扱いやすい',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV018',
    purchaseInfo: {
      purchaseDate: '2025-01-19',
      purchaseType: '下取',
      supplier: '顧客：橋本信一様',
      expectedArrivalDate: '2025-01-21',
      arrivalDate: '2025-01-21',
      notifyOnDelay: false,
      purchaseManager: '佐藤',
      store: '支店B',
      depositStatus: '不要',
      depositAmount: 0,
      purchasePrice: 480000,
      legalFees: [],
      options: [],
      autoTax: 25000,
      autoTaxEnv: 0,
      weightTax: 12300,
      compulsoryInsurance: 17540,
      voluntaryInsurance: 0,
      totalAmount: 534840,
    },
    vehicleInfo: {
      vinNumber: '77889900112233445',
      carModel: 'ミライース',
      maker: 'ダイハツ',
      color: 'ホワイト',
      grade: 'L',
      year: '2018',
      mileage: '55000',
      modelType: 'LA350S',
      referencePrice: 580000,
    },
    salesInfo: {
      displayLocation: '支店B 1F',
      salesPrice: 720000,
      onlinePosted: true,
      notes: '低燃費エコカー',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV019',
    purchaseInfo: {
      purchaseDate: '2025-01-20',
      purchaseType: 'オークション',
      supplier: 'TAA横浜',
      expectedArrivalDate: '2025-01-25',
      arrivalDate: '',
      notifyOnDelay: true,
      purchaseManager: '高橋',
      store: '支店A',
      depositStatus: '預託済',
      depositAmount: 70000,
      purchasePrice: 1900000,
      legalFees: [
        { id: 'lf22', category: '自動車税', amount: 51000 },
        { id: 'lf23', category: '重量税', amount: 32800 },
      ],
      options: [
        { id: 'opt11', category: '外装', optionName: 'コーティング', amount: 45000 },
      ],
      autoTax: 51000,
      autoTaxEnv: 0,
      weightTax: 32800,
      compulsoryInsurance: 25830,
      voluntaryInsurance: 0,
      totalAmount: 2054630,
    },
    vehicleInfo: {
      vinNumber: '88990011223344556',
      carModel: 'RAV4',
      maker: 'トヨタ',
      color: 'シルバーメタリック',
      grade: 'G',
      year: '2021',
      mileage: '25000',
      modelType: 'MXAA54',
      referencePrice: 2300000,
    },
    salesInfo: {
      displayLocation: '入庫待ち',
      salesPrice: 2880000,
      onlinePosted: false,
      notes: '人気のSUV',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV020',
    purchaseInfo: {
      purchaseDate: '2025-01-21',
      purchaseType: 'オークション',
      supplier: 'JU大阪',
      expectedArrivalDate: '2025-01-26',
      arrivalDate: '',
      notifyOnDelay: true,
      purchaseManager: '田中',
      store: '本店',
      depositStatus: '預託済',
      depositAmount: 48000,
      purchasePrice: 980000,
      legalFees: [],
      options: [],
      autoTax: 34500,
      autoTaxEnv: 0,
      weightTax: 20500,
      compulsoryInsurance: 20010,
      voluntaryInsurance: 0,
      totalAmount: 1055010,
    },
    vehicleInfo: {
      vinNumber: '99001122334455667',
      carModel: 'スイフト',
      maker: 'スズキ',
      color: 'バーニングレッドパールメタリック',
      grade: 'RS',
      year: '2020',
      mileage: '32000',
      modelType: 'ZC33S',
      referencePrice: 1150000,
    },
    salesInfo: {
      displayLocation: '入庫待ち',
      salesPrice: 1420000,
      onlinePosted: false,
      notes: 'スポーティなコンパクト',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV021',
    purchaseInfo: {
      purchaseDate: '2025-01-10',
      purchaseType: '下取',
      supplier: '顧客：石川美咲様',
      expectedArrivalDate: '2025-01-13',
      arrivalDate: '2025-01-13',
      notifyOnDelay: false,
      purchaseManager: '鈴木',
      store: '本店',
      depositStatus: '不要',
      depositAmount: 0,
      purchasePrice: 620000,
      legalFees: [],
      options: [],
      autoTax: 29500,
      autoTaxEnv: 0,
      weightTax: 16400,
      compulsoryInsurance: 20010,
      voluntaryInsurance: 0,
      totalAmount: 685910,
    },
    vehicleInfo: {
      vinNumber: '00112233445566778',
      carModel: 'デミオ',
      maker: 'マツダ',
      color: 'ソウルレッドクリスタルメタリック',
      grade: '13S',
      year: '2018',
      mileage: '52000',
      modelType: 'DJ5FS',
      referencePrice: 750000,
    },
    salesInfo: {
      displayLocation: '本店1F',
      salesPrice: 950000,
      onlinePosted: true,
      notes: '質感高いコンパクト',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV022',
    purchaseInfo: {
      purchaseDate: '2025-01-11',
      purchaseType: 'オークション',
      supplier: 'AA名古屋会場',
      expectedArrivalDate: '2025-01-16',
      arrivalDate: '2025-01-16',
      notifyOnDelay: true,
      purchaseManager: '佐藤',
      store: '支店A',
      depositStatus: '預託済',
      depositAmount: 52000,
      purchasePrice: 1150000,
      legalFees: [
        { id: 'lf24', category: '自動車税', amount: 39500 },
      ],
      options: [
        { id: 'opt12', category: 'ナビ', optionName: 'カーナビ', amount: 30000 },
      ],
      autoTax: 39500,
      autoTaxEnv: 0,
      weightTax: 24600,
      compulsoryInsurance: 25830,
      voluntaryInsurance: 0,
      totalAmount: 1269930,
    },
    vehicleInfo: {
      vinNumber: '11223344556677880',
      carModel: 'CX-5',
      maker: 'マツダ',
      color: 'ソニックシルバーメタリック',
      grade: '20S',
      year: '2019',
      mileage: '44000',
      modelType: 'KF5P',
      referencePrice: 1450000,
    },
    salesInfo: {
      displayLocation: '支店A 2F',
      salesPrice: 1880000,
      onlinePosted: true,
      notes: '洗練されたSUV',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV023',
    purchaseInfo: {
      purchaseDate: '2025-01-22',
      purchaseType: 'オークション',
      supplier: 'USS東京',
      expectedArrivalDate: '2025-01-27',
      arrivalDate: '',
      notifyOnDelay: true,
      purchaseManager: '高橋',
      store: '支店B',
      depositStatus: '預託済',
      depositAmount: 42000,
      purchasePrice: 870000,
      legalFees: [],
      options: [],
      autoTax: 34500,
      autoTaxEnv: 0,
      weightTax: 20500,
      compulsoryInsurance: 20010,
      voluntaryInsurance: 0,
      totalAmount: 945010,
    },
    vehicleInfo: {
      vinNumber: '22334455667788991',
      carModel: 'ヴィッツ',
      maker: 'トヨタ',
      color: 'スーパーホワイトⅡ',
      grade: 'F',
      year: '2017',
      mileage: '58000',
      modelType: 'NSP130',
      referencePrice: 1000000,
    },
    salesInfo: {
      displayLocation: '入庫待ち',
      salesPrice: 1250000,
      onlinePosted: false,
      notes: '定番コンパクトカー',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV024',
    purchaseInfo: {
      purchaseDate: '2025-01-09',
      purchaseType: '下取',
      supplier: '顧客：長谷川浩二様',
      expectedArrivalDate: '2025-01-12',
      arrivalDate: '2025-01-12',
      notifyOnDelay: false,
      purchaseManager: '田中',
      store: '本店',
      depositStatus: '不要',
      depositAmount: 0,
      purchasePrice: 1250000,
      legalFees: [],
      options: [],
      autoTax: 39500,
      autoTaxEnv: 0,
      weightTax: 24600,
      compulsoryInsurance: 25830,
      voluntaryInsurance: 0,
      totalAmount: 1339930,
    },
    vehicleInfo: {
      vinNumber: '33445566778899002',
      carModel: 'レヴォーグ',
      maker: 'スバル',
      color: 'クリスタルホワイトパール',
      grade: '1.6GT EyeSight',
      year: '2020',
      mileage: '36000',
      modelType: 'VM4',
      referencePrice: 1550000,
    },
    salesInfo: {
      displayLocation: '本店2F',
      salesPrice: 1980000,
      onlinePosted: true,
      notes: 'スポーツワゴン',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV025',
    purchaseInfo: {
      purchaseDate: '2025-01-23',
      purchaseType: 'オークション',
      supplier: 'JU大阪',
      expectedArrivalDate: '2025-01-28',
      arrivalDate: '',
      notifyOnDelay: true,
      purchaseManager: '鈴木',
      store: '支店A',
      depositStatus: '預託済',
      depositAmount: 38000,
      purchasePrice: 780000,
      legalFees: [],
      options: [],
      autoTax: 29500,
      autoTaxEnv: 0,
      weightTax: 16400,
      compulsoryInsurance: 20010,
      voluntaryInsurance: 0,
      totalAmount: 845910,
    },
    vehicleInfo: {
      vinNumber: '44556677889900113',
      carModel: 'パッソ',
      maker: 'トヨタ',
      color: 'マゼンタベリーマイカメタリック',
      grade: 'X',
      year: '2019',
      mileage: '46000',
      modelType: 'M700A',
      referencePrice: 880000,
    },
    salesInfo: {
      displayLocation: '入庫待ち',
      salesPrice: 1120000,
      onlinePosted: false,
      notes: '女性に人気',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV026',
    purchaseInfo: {
      purchaseDate: '2025-01-08',
      purchaseType: 'オークション',
      supplier: 'TAA横浜',
      expectedArrivalDate: '2025-01-13',
      arrivalDate: '2025-01-14',
      notifyOnDelay: true,
      purchaseManager: '佐藤',
      store: '本店',
      depositStatus: '預託済',
      depositAmount: 60000,
      purchasePrice: 1600000,
      legalFees: [
        { id: 'lf25', category: '自動車税', amount: 45000 },
        { id: 'lf26', category: '重量税', amount: 32800 },
      ],
      options: [
        { id: 'opt13', category: '外装', optionName: 'エアロパーツ', amount: 80000 },
      ],
      autoTax: 45000,
      autoTaxEnv: 0,
      weightTax: 32800,
      compulsoryInsurance: 25830,
      voluntaryInsurance: 0,
      totalAmount: 1783630,
    },
    vehicleInfo: {
      vinNumber: '55667788990011224',
      carModel: 'ステップワゴン',
      maker: 'ホンダ',
      color: 'プラチナホワイトパール',
      grade: 'スパーダ',
      year: '2020',
      mileage: '38000',
      modelType: 'RP5',
      referencePrice: 1950000,
    },
    salesInfo: {
      displayLocation: '本店1F',
      salesPrice: 2380000,
      onlinePosted: true,
      notes: 'ファミリー向けミニバン',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV027',
    purchaseInfo: {
      purchaseDate: '2025-01-24',
      purchaseType: '下取',
      supplier: '顧客：森田達也様',
      expectedArrivalDate: '2025-01-26',
      arrivalDate: '',
      notifyOnDelay: false,
      purchaseManager: '高橋',
      store: '支店B',
      depositStatus: '不要',
      depositAmount: 0,
      purchasePrice: 520000,
      legalFees: [],
      options: [],
      autoTax: 25000,
      autoTaxEnv: 0,
      weightTax: 12300,
      compulsoryInsurance: 17540,
      voluntaryInsurance: 0,
      totalAmount: 574840,
    },
    vehicleInfo: {
      vinNumber: '66778899001122335',
      carModel: 'ワゴンR',
      maker: 'スズキ',
      color: 'シルキーシルバーメタリック',
      grade: 'FX',
      year: '2018',
      mileage: '59000',
      modelType: 'MH35S',
      referencePrice: 620000,
    },
    salesInfo: {
      displayLocation: '入庫待ち',
      salesPrice: 780000,
      onlinePosted: false,
      notes: '定番の軽自動車',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV028',
    purchaseInfo: {
      purchaseDate: '2025-01-07',
      purchaseType: 'オークション',
      supplier: 'AA名古屋会場',
      expectedArrivalDate: '2025-01-12',
      arrivalDate: '2025-01-12',
      notifyOnDelay: true,
      purchaseManager: '田中',
      store: '支店A',
      depositStatus: '預託済',
      depositAmount: 75000,
      purchasePrice: 2100000,
      legalFees: [
        { id: 'lf27', category: '自動車税', amount: 51000 },
      ],
      options: [
        { id: 'opt14', category: 'ナビ', optionName: '高級カーナビ', amount: 120000 },
        { id: 'opt15', category: '内装', optionName: 'レザーシート', amount: 150000 },
      ],
      autoTax: 51000,
      autoTaxEnv: 0,
      weightTax: 32800,
      compulsoryInsurance: 25830,
      voluntaryInsurance: 0,
      totalAmount: 2479630,
    },
    vehicleInfo: {
      vinNumber: '77889900112233446',
      carModel: 'クラウン',
      maker: 'トヨタ',
      color: 'プレシャスブラックパール',
      grade: 'RS',
      year: '2021',
      mileage: '22000',
      modelType: 'AZSH21',
      referencePrice: 2800000,
    },
    salesInfo: {
      displayLocation: '支店A 1F',
      salesPrice: 3380000,
      onlinePosted: true,
      notes: '高級セダン',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV029',
    purchaseInfo: {
      purchaseDate: '2025-01-25',
      purchaseType: 'オークション',
      supplier: 'USS東京',
      expectedArrivalDate: '2025-01-30',
      arrivalDate: '',
      notifyOnDelay: true,
      purchaseManager: '鈴木',
      store: '本店',
      depositStatus: '預託済',
      depositAmount: 35000,
      purchasePrice: 720000,
      legalFees: [],
      options: [],
      autoTax: 29500,
      autoTaxEnv: 0,
      weightTax: 16400,
      compulsoryInsurance: 20010,
      voluntaryInsurance: 0,
      totalAmount: 785910,
    },
    vehicleInfo: {
      vinNumber: '88990011223344557',
      carModel: 'ルーミー',
      maker: 'トヨタ',
      color: 'ブラックマイカメタリック',
      grade: 'X',
      year: '2018',
      mileage: '54000',
      modelType: 'M900A',
      referencePrice: 850000,
    },
    salesInfo: {
      displayLocation: '入庫待ち',
      salesPrice: 1080000,
      onlinePosted: false,
      notes: '広々コンパクトカー',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV030',
    purchaseInfo: {
      purchaseDate: '2025-01-06',
      purchaseType: '下取',
      supplier: '顧客：小林由美様',
      expectedArrivalDate: '2025-01-09',
      arrivalDate: '2025-01-09',
      notifyOnDelay: false,
      purchaseManager: '佐藤',
      store: '支店A',
      depositStatus: '不要',
      depositAmount: 0,
      purchasePrice: 950000,
      legalFees: [],
      options: [],
      autoTax: 34500,
      autoTaxEnv: 0,
      weightTax: 20500,
      compulsoryInsurance: 20010,
      voluntaryInsurance: 0,
      totalAmount: 1025010,
    },
    vehicleInfo: {
      vinNumber: '99001122334455668',
      carModel: 'インプレッサスポーツ',
      maker: 'スバル',
      color: 'アイスシルバーメタリック',
      grade: '1.6i-L EyeSight',
      year: '2019',
      mileage: '42000',
      modelType: 'GT2',
      referencePrice: 1150000,
    },
    salesInfo: {
      displayLocation: '支店A 2F',
      salesPrice: 1480000,
      onlinePosted: true,
      notes: '安全性能充実',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV031',
    purchaseInfo: {
      purchaseDate: '2025-01-26',
      purchaseType: 'オークション',
      supplier: 'TAA横浜',
      expectedArrivalDate: '2025-01-31',
      arrivalDate: '',
      notifyOnDelay: true,
      purchaseManager: '高橋',
      store: '本店',
      depositStatus: '預託済',
      depositAmount: 43000,
      purchasePrice: 890000,
      legalFees: [],
      options: [],
      autoTax: 34500,
      autoTaxEnv: 0,
      weightTax: 20500,
      compulsoryInsurance: 20010,
      voluntaryInsurance: 0,
      totalAmount: 965010,
    },
    vehicleInfo: {
      vinNumber: '00112233445566779',
      carModel: 'ソリオ',
      maker: 'スズキ',
      color: 'スピーディーブルーメタリック',
      grade: 'G',
      year: '2019',
      mileage: '40000',
      modelType: 'MA37S',
      referencePrice: 1050000,
    },
    salesInfo: {
      displayLocation: '入庫待ち',
      salesPrice: 1320000,
      onlinePosted: false,
      notes: '使い勝手の良いハイトワゴン',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV032',
    purchaseInfo: {
      purchaseDate: '2025-01-05',
      purchaseType: 'オークション',
      supplier: 'JU大阪',
      expectedArrivalDate: '2025-01-10',
      arrivalDate: '2025-01-11',
      notifyOnDelay: true,
      purchaseManager: '田中',
      store: '支店B',
      depositStatus: '預託済',
      depositAmount: 55000,
      purchasePrice: 1200000,
      legalFees: [
        { id: 'lf28', category: '自動車税', amount: 39500 },
      ],
      options: [
        { id: 'opt16', category: 'ナビ', optionName: 'カーナビ', amount: 40000 },
      ],
      autoTax: 39500,
      autoTaxEnv: 0,
      weightTax: 24600,
      compulsoryInsurance: 25830,
      voluntaryInsurance: 0,
      totalAmount: 1329930,
    },
    vehicleInfo: {
      vinNumber: '11223344556677881',
      carModel: 'ヴェゼル',
      maker: 'ホンダ',
      color: 'プレミアムクリスタルレッドメタリック',
      grade: 'X',
      year: '2020',
      mileage: '34000',
      modelType: 'RU3',
      referencePrice: 1500000,
    },
    salesInfo: {
      displayLocation: '支店B 1F',
      salesPrice: 1880000,
      onlinePosted: true,
      notes: 'コンパクトSUV',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV033',
    purchaseInfo: {
      purchaseDate: '2025-01-27',
      purchaseType: '下取',
      supplier: '顧客：井上美香様',
      expectedArrivalDate: '2025-01-29',
      arrivalDate: '',
      notifyOnDelay: false,
      purchaseManager: '鈴木',
      store: '支店A',
      depositStatus: '不要',
      depositAmount: 0,
      purchasePrice: 680000,
      legalFees: [],
      options: [],
      autoTax: 29500,
      autoTaxEnv: 0,
      weightTax: 16400,
      compulsoryInsurance: 20010,
      voluntaryInsurance: 0,
      totalAmount: 745910,
    },
    vehicleInfo: {
      vinNumber: '22334455667788992',
      carModel: 'ピクシススペース',
      maker: 'トヨタ',
      color: 'パールホワイト',
      grade: 'X',
      year: '2017',
      mileage: '61000',
      modelType: 'L575A',
      referencePrice: 750000,
    },
    salesInfo: {
      displayLocation: '入庫待ち',
      salesPrice: 980000,
      onlinePosted: false,
      notes: '広い軽自動車',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV034',
    purchaseInfo: {
      purchaseDate: '2025-01-04',
      purchaseType: 'オークション',
      supplier: 'AA名古屋会場',
      expectedArrivalDate: '2025-01-09',
      arrivalDate: '2025-01-10',
      notifyOnDelay: true,
      purchaseManager: '佐藤',
      store: '本店',
      depositStatus: '預託済',
      depositAmount: 68000,
      purchasePrice: 1850000,
      legalFees: [
        { id: 'lf29', category: '自動車税', amount: 51000 },
        { id: 'lf30', category: '重量税', amount: 32800 },
      ],
      options: [
        { id: 'opt17', category: '外装', optionName: 'コーティング', amount: 50000 },
      ],
      autoTax: 51000,
      autoTaxEnv: 0,
      weightTax: 32800,
      compulsoryInsurance: 25830,
      voluntaryInsurance: 0,
      totalAmount: 2009630,
    },
    vehicleInfo: {
      vinNumber: '33445566778899003',
      carModel: 'オデッセイ',
      maker: 'ホンダ',
      color: 'プラチナホワイトパール',
      grade: 'アブソルート',
      year: '2021',
      mileage: '27000',
      modelType: 'RC1',
      referencePrice: 2200000,
    },
    salesInfo: {
      displayLocation: '本店1F',
      salesPrice: 2780000,
      onlinePosted: true,
      notes: '上質なミニバン',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV035',
    purchaseInfo: {
      purchaseDate: '2025-01-28',
      purchaseType: 'オークション',
      supplier: 'USS東京',
      expectedArrivalDate: '2025-02-02',
      arrivalDate: '',
      notifyOnDelay: true,
      purchaseManager: '高橋',
      store: '支店A',
      depositStatus: '預託済',
      depositAmount: 39000,
      purchasePrice: 810000,
      legalFees: [],
      options: [],
      autoTax: 29500,
      autoTaxEnv: 0,
      weightTax: 16400,
      compulsoryInsurance: 20010,
      voluntaryInsurance: 0,
      totalAmount: 875910,
    },
    vehicleInfo: {
      vinNumber: '44556677889900114',
      carModel: 'ポルテ',
      maker: 'トヨタ',
      color: 'ホワイトパールクリスタルシャイン',
      grade: 'X',
      year: '2018',
      mileage: '50000',
      modelType: 'NSP141',
      referencePrice: 920000,
    },
    salesInfo: {
      displayLocation: '入庫待ち',
      salesPrice: 1150000,
      onlinePosted: false,
      notes: '乗り降りしやすい',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV036',
    purchaseInfo: {
      purchaseDate: '2025-01-03',
      purchaseType: '下取',
      supplier: '顧客：木村隆様',
      expectedArrivalDate: '2025-01-06',
      arrivalDate: '2025-01-06',
      notifyOnDelay: false,
      purchaseManager: '田中',
      store: '支店B',
      depositStatus: '不要',
      depositAmount: 0,
      purchasePrice: 1050000,
      legalFees: [],
      options: [],
      autoTax: 39500,
      autoTaxEnv: 0,
      weightTax: 24600,
      compulsoryInsurance: 25830,
      voluntaryInsurance: 0,
      totalAmount: 1139930,
    },
    vehicleInfo: {
      vinNumber: '55667788990011225',
      carModel: 'シエンタ',
      maker: 'トヨタ',
      color: 'ブラックマイカ',
      grade: 'X',
      year: '2019',
      mileage: '45000',
      modelType: 'NSP170G',
      referencePrice: 1280000,
    },
    salesInfo: {
      displayLocation: '支店B 2F',
      salesPrice: 1650000,
      onlinePosted: true,
      notes: 'コンパクトミニバン',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV037',
    purchaseInfo: {
      purchaseDate: '2025-01-29',
      purchaseType: 'オークション',
      supplier: 'TAA横浜',
      expectedArrivalDate: '2025-02-03',
      arrivalDate: '',
      notifyOnDelay: true,
      purchaseManager: '鈴木',
      store: '本店',
      depositStatus: '預託済',
      depositAmount: 46000,
      purchasePrice: 950000,
      legalFees: [],
      options: [],
      autoTax: 34500,
      autoTaxEnv: 0,
      weightTax: 20500,
      compulsoryInsurance: 20010,
      voluntaryInsurance: 0,
      totalAmount: 1025010,
    },
    vehicleInfo: {
      vinNumber: '66778899001122336',
      carModel: 'ラクティス',
      maker: 'トヨタ',
      color: 'シルバーメタリック',
      grade: 'G',
      year: '2016',
      mileage: '64000',
      modelType: 'NCP120',
      referencePrice: 1050000,
    },
    salesInfo: {
      displayLocation: '入庫待ち',
      salesPrice: 1280000,
      onlinePosted: false,
      notes: '実用的なハッチバック',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV038',
    purchaseInfo: {
      purchaseDate: '2025-01-02',
      purchaseType: 'オークション',
      supplier: 'JU大阪',
      expectedArrivalDate: '2025-01-07',
      arrivalDate: '2025-01-08',
      notifyOnDelay: true,
      purchaseManager: '佐藤',
      store: '支店A',
      depositStatus: '預託済',
      depositAmount: 72000,
      purchasePrice: 2050000,
      legalFees: [
        { id: 'lf31', category: '自動車税', amount: 51000 },
      ],
      options: [
        { id: 'opt18', category: 'ナビ', optionName: 'プレミアムナビ', amount: 100000 },
        { id: 'opt19', category: '内装', optionName: 'シートヒーター', amount: 40000 },
      ],
      autoTax: 51000,
      autoTaxEnv: 0,
      weightTax: 32800,
      compulsoryInsurance: 25830,
      voluntaryInsurance: 0,
      totalAmount: 2299630,
    },
    vehicleInfo: {
      vinNumber: '77889900112233447',
      carModel: 'レクサスNX',
      maker: 'トヨタ',
      color: 'ソニックチタニウム',
      grade: 'NX300',
      year: '2021',
      mileage: '24000',
      modelType: 'AGZ15',
      referencePrice: 2650000,
    },
    salesInfo: {
      displayLocation: '支店A 1F',
      salesPrice: 3280000,
      onlinePosted: true,
      notes: 'プレミアムSUV',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV039',
    purchaseInfo: {
      purchaseDate: '2025-01-30',
      purchaseType: '下取',
      supplier: '顧客：渡辺真理子様',
      expectedArrivalDate: '2025-02-01',
      arrivalDate: '',
      notifyOnDelay: false,
      purchaseManager: '高橋',
      store: '本店',
      depositStatus: '不要',
      depositAmount: 0,
      purchasePrice: 590000,
      legalFees: [],
      options: [],
      autoTax: 25000,
      autoTaxEnv: 0,
      weightTax: 12300,
      compulsoryInsurance: 17540,
      voluntaryInsurance: 0,
      totalAmount: 644840,
    },
    vehicleInfo: {
      vinNumber: '88990011223344558',
      carModel: 'アルト',
      maker: 'スズキ',
      color: 'ピュアホワイトパール',
      grade: 'L',
      year: '2018',
      mileage: '56000',
      modelType: 'HA36S',
      referencePrice: 680000,
    },
    salesInfo: {
      displayLocation: '入庫待ち',
      salesPrice: 850000,
      onlinePosted: false,
      notes: '低価格軽自動車',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV040',
    purchaseInfo: {
      purchaseDate: '2025-01-01',
      purchaseType: 'オークション',
      supplier: 'AA名古屋会場',
      expectedArrivalDate: '2025-01-06',
      arrivalDate: '2025-01-07',
      notifyOnDelay: true,
      purchaseManager: '田中',
      store: '本店',
      depositStatus: '預託済',
      depositAmount: 58000,
      purchasePrice: 1350000,
      legalFees: [
        { id: 'lf32', category: '自動車税', amount: 39500 },
      ],
      options: [
        { id: 'opt20', category: 'ナビ', optionName: 'カーナビ', amount: 35000 },
      ],
      autoTax: 39500,
      autoTaxEnv: 0,
      weightTax: 24600,
      compulsoryInsurance: 25830,
      voluntaryInsurance: 0,
      totalAmount: 1474930,
    },
    vehicleInfo: {
      vinNumber: '99001122334455669',
      carModel: 'アクセラスポーツ',
      maker: 'マツダ',
      color: 'ソウルレッドクリスタルメタリック',
      grade: '15S',
      year: '2019',
      mileage: '39000',
      modelType: 'BM5FS',
      referencePrice: 1550000,
    },
    salesInfo: {
      displayLocation: '本店2F',
      salesPrice: 1880000,
      onlinePosted: true,
      notes: 'スポーティなハッチバック',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV041',
    purchaseInfo: {
      purchaseDate: '2024-12-30',
      purchaseType: 'オークション',
      supplier: 'USS東京',
      expectedArrivalDate: '2025-01-05',
      arrivalDate: '2025-01-05',
      notifyOnDelay: true,
      purchaseManager: '鈴木',
      store: '支店B',
      depositStatus: '預託済',
      depositAmount: 41000,
      purchasePrice: 860000,
      legalFees: [],
      options: [],
      autoTax: 34500,
      autoTaxEnv: 0,
      weightTax: 20500,
      compulsoryInsurance: 20010,
      voluntaryInsurance: 0,
      totalAmount: 935010,
    },
    vehicleInfo: {
      vinNumber: '00112233445566770',
      carModel: 'キューブ',
      maker: '日産',
      color: 'ブリリアントシルバー',
      grade: '15X',
      year: '2017',
      mileage: '63000',
      modelType: 'Z12',
      referencePrice: 950000,
    },
    salesInfo: {
      displayLocation: '支店B 1F',
      salesPrice: 1180000,
      onlinePosted: true,
      notes: '個性的なデザイン',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV042',
    purchaseInfo: {
      purchaseDate: '2024-12-29',
      purchaseType: '下取',
      supplier: '顧客：加藤誠様',
      expectedArrivalDate: '2025-01-02',
      arrivalDate: '2025-01-02',
      notifyOnDelay: false,
      purchaseManager: '佐藤',
      store: '支店B',
      depositStatus: '不要',
      depositAmount: 0,
      purchasePrice: 1100000,
      legalFees: [],
      options: [],
      autoTax: 39500,
      autoTaxEnv: 0,
      weightTax: 24600,
      compulsoryInsurance: 25830,
      voluntaryInsurance: 0,
      totalAmount: 1189930,
    },
    vehicleInfo: {
      vinNumber: '11223344556677882',
      carModel: 'フリード',
      maker: 'ホンダ',
      color: 'ホワイトオーキッドパール',
      grade: 'G',
      year: '2019',
      mileage: '43000',
      modelType: 'GB5',
      referencePrice: 1350000,
    },
    salesInfo: {
      displayLocation: '支店B 2F',
      salesPrice: 1780000,
      onlinePosted: true,
      notes: 'コンパクトミニバン',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV043',
    purchaseInfo: {
      purchaseDate: '2024-12-28',
      purchaseType: 'オークション',
      supplier: 'TAA横浜',
      expectedArrivalDate: '2025-01-04',
      arrivalDate: '2025-01-04',
      notifyOnDelay: true,
      purchaseManager: '高橋',
      store: '本店',
      depositStatus: '預託済',
      depositAmount: 49000,
      purchasePrice: 1020000,
      legalFees: [],
      options: [],
      autoTax: 34500,
      autoTaxEnv: 0,
      weightTax: 20500,
      compulsoryInsurance: 20010,
      voluntaryInsurance: 0,
      totalAmount: 1095010,
    },
    vehicleInfo: {
      vinNumber: '22334455667788993',
      carModel: 'タンク',
      maker: 'トヨタ',
      color: 'ブラックマイカメタリック',
      grade: 'X',
      year: '2018',
      mileage: '51000',
      modelType: 'M900A',
      referencePrice: 1150000,
    },
    salesInfo: {
      displayLocation: '本店1F',
      salesPrice: 1380000,
      onlinePosted: true,
      notes: '使いやすいトールワゴン',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV044',
    purchaseInfo: {
      purchaseDate: '2024-12-27',
      purchaseType: 'オークション',
      supplier: 'JU大阪',
      expectedArrivalDate: '2025-01-03',
      arrivalDate: '2025-01-03',
      notifyOnDelay: true,
      purchaseManager: '田中',
      store: '支店A',
      depositStatus: '預託済',
      depositAmount: 63000,
      purchasePrice: 1700000,
      legalFees: [
        { id: 'lf33', category: '自動車税', amount: 45000 },
        { id: 'lf34', category: '重量税', amount: 32800 },
      ],
      options: [
        { id: 'opt21', category: '外装', optionName: 'コーティング', amount: 55000 },
      ],
      autoTax: 45000,
      autoTaxEnv: 0,
      weightTax: 32800,
      compulsoryInsurance: 25830,
      voluntaryInsurance: 0,
      totalAmount: 1858630,
    },
    vehicleInfo: {
      vinNumber: '33445566778899004',
      carModel: 'フォレスター',
      maker: 'スバル',
      color: 'ダークグレーメタリック',
      grade: 'Touring',
      year: '2020',
      mileage: '31000',
      modelType: 'SK9',
      referencePrice: 2000000,
    },
    salesInfo: {
      displayLocation: '支店A 1F',
      salesPrice: 2480000,
      onlinePosted: true,
      notes: 'アウトドア向けSUV',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV045',
    purchaseInfo: {
      purchaseDate: '2024-12-26',
      purchaseType: '下取',
      supplier: '顧客：中村健太様',
      expectedArrivalDate: '2024-12-29',
      arrivalDate: '2024-12-29',
      notifyOnDelay: false,
      purchaseManager: '鈴木',
      store: '本店',
      depositStatus: '不要',
      depositAmount: 0,
      purchasePrice: 700000,
      legalFees: [],
      options: [],
      autoTax: 29500,
      autoTaxEnv: 0,
      weightTax: 16400,
      compulsoryInsurance: 20010,
      voluntaryInsurance: 0,
      totalAmount: 765910,
    },
    vehicleInfo: {
      vinNumber: '44556677889900115',
      carModel: 'ブーン',
      maker: 'ダイハツ',
      color: 'ホワイト',
      grade: 'X',
      year: '2017',
      mileage: '60000',
      modelType: 'M700S',
      referencePrice: 780000,
    },
    salesInfo: {
      displayLocation: '本店2F',
      salesPrice: 980000,
      onlinePosted: true,
      notes: 'コンパクトで経済的',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV046',
    purchaseInfo: {
      purchaseDate: '2024-12-25',
      purchaseType: 'オークション',
      supplier: 'AA名古屋会場',
      expectedArrivalDate: '2024-12-31',
      arrivalDate: '2025-01-01',
      notifyOnDelay: true,
      purchaseManager: '佐藤',
      store: '支店B',
      depositStatus: '預託済',
      depositAmount: 51000,
      purchasePrice: 1120000,
      legalFees: [
        { id: 'lf35', category: '自動車税', amount: 39500 },
      ],
      options: [],
      autoTax: 39500,
      autoTaxEnv: 0,
      weightTax: 24600,
      compulsoryInsurance: 25830,
      voluntaryInsurance: 0,
      totalAmount: 1209930,
    },
    vehicleInfo: {
      vinNumber: '55667788990011226',
      carModel: 'ジューク',
      maker: '日産',
      color: 'ラディアントレッド',
      grade: '15RX',
      year: '2019',
      mileage: '44000',
      modelType: 'F15',
      referencePrice: 1300000,
    },
    salesInfo: {
      displayLocation: '支店B 1F',
      salesPrice: 1580000,
      onlinePosted: true,
      notes: '個性的なコンパクトSUV',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV047',
    purchaseInfo: {
      purchaseDate: '2024-12-24',
      purchaseType: 'オークション',
      supplier: 'USS東京',
      expectedArrivalDate: '2024-12-30',
      arrivalDate: '2024-12-30',
      notifyOnDelay: true,
      purchaseManager: '高橋',
      store: '本店',
      depositStatus: '預託済',
      depositAmount: 66000,
      purchasePrice: 1800000,
      legalFees: [
        { id: 'lf36', category: '自動車税', amount: 51000 },
      ],
      options: [
        { id: 'opt22', category: 'ナビ', optionName: 'カーナビ', amount: 45000 },
        { id: 'opt23', category: '内装', optionName: 'シートカバー', amount: 20000 },
      ],
      autoTax: 51000,
      autoTaxEnv: 0,
      weightTax: 32800,
      compulsoryInsurance: 25830,
      voluntaryInsurance: 0,
      totalAmount: 1974630,
    },
    vehicleInfo: {
      vinNumber: '66778899001122337',
      carModel: 'デリカD:5',
      maker: '三菱',
      color: 'ブラックマイカ',
      grade: 'M',
      year: '2020',
      mileage: '35000',
      modelType: 'CV1W',
      referencePrice: 2150000,
    },
    salesInfo: {
      displayLocation: '本店1F',
      salesPrice: 2680000,
      onlinePosted: true,
      notes: 'アウトドア向けミニバン',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV048',
    purchaseInfo: {
      purchaseDate: '2024-12-23',
      purchaseType: '下取',
      supplier: '顧客：山口大輔様',
      expectedArrivalDate: '2024-12-26',
      arrivalDate: '2024-12-26',
      notifyOnDelay: false,
      purchaseManager: '田中',
      store: '支店A',
      depositStatus: '不要',
      depositAmount: 0,
      purchasePrice: 920000,
      legalFees: [],
      options: [],
      autoTax: 34500,
      autoTaxEnv: 0,
      weightTax: 20500,
      compulsoryInsurance: 20010,
      voluntaryInsurance: 0,
      totalAmount: 995010,
    },
    vehicleInfo: {
      vinNumber: '77889900112233448',
      carModel: 'イグニス',
      maker: 'スズキ',
      color: 'フェニックスレッドパール',
      grade: 'ハイブリッドMZ',
      year: '2019',
      mileage: '41000',
      modelType: 'FF21S',
      referencePrice: 1050000,
    },
    salesInfo: {
      displayLocation: '支店A 2F',
      salesPrice: 1320000,
      onlinePosted: true,
      notes: 'コンパクトクロスオーバー',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV049',
    purchaseInfo: {
      purchaseDate: '2024-12-22',
      purchaseType: 'オークション',
      supplier: 'TAA横浜',
      expectedArrivalDate: '2024-12-28',
      arrivalDate: '2024-12-28',
      notifyOnDelay: true,
      purchaseManager: '鈴木',
      store: '支店B',
      depositStatus: '預託済',
      depositAmount: 44000,
      purchasePrice: 910000,
      legalFees: [],
      options: [],
      autoTax: 34500,
      autoTaxEnv: 0,
      weightTax: 20500,
      compulsoryInsurance: 20010,
      voluntaryInsurance: 0,
      totalAmount: 985010,
    },
    vehicleInfo: {
      vinNumber: '88990011223344559',
      carModel: 'トレジア',
      maker: 'トヨタ',
      color: 'シルバーメタリック',
      grade: '1.5i',
      year: '2016',
      mileage: '67000',
      modelType: 'NCP120X',
      referencePrice: 1000000,
    },
    salesInfo: {
      displayLocation: '支店B 2F',
      salesPrice: 1250000,
      onlinePosted: true,
      notes: '実用的なコンパクト',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
  {
    id: 'INV050',
    purchaseInfo: {
      purchaseDate: '2024-12-21',
      purchaseType: 'オークション',
      supplier: 'JU大阪',
      expectedArrivalDate: '2024-12-27',
      arrivalDate: '2024-12-27',
      notifyOnDelay: true,
      purchaseManager: '佐藤',
      store: '本店',
      depositStatus: '預託済',
      depositAmount: 78000,
      purchasePrice: 2300000,
      legalFees: [
        { id: 'lf37', category: '自動車税', amount: 58000 },
        { id: 'lf38', category: '重量税', amount: 49200 },
      ],
      options: [
        { id: 'opt24', category: 'ナビ', optionName: 'プレミアムナビ', amount: 150000 },
        { id: 'opt25', category: '内装', optionName: 'レザーシート', amount: 200000 },
        { id: 'opt26', category: '外装', optionName: 'プレミアムコーティング', amount: 80000 },
      ],
      autoTax: 58000,
      autoTaxEnv: 0,
      weightTax: 49200,
      compulsoryInsurance: 25830,
      voluntaryInsurance: 0,
      totalAmount: 2870030,
    },
    vehicleInfo: {
      vinNumber: '99001122334455660',
      carModel: 'レクサスRX',
      maker: 'トヨタ',
      color: 'グラファイトブラックガラスフレーク',
      grade: 'RX300',
      year: '2022',
      mileage: '18000',
      modelType: 'AGL25',
      referencePrice: 3500000,
    },
    salesInfo: {
      displayLocation: '本店1F',
      salesPrice: 4280000,
      onlinePosted: true,
      notes: '最高級プレミアムSUV',
    },
    status: 'available',
    customerId: null,
    reservedDate: '',
    soldDate: '',
  },
]
